### ISSUE TITLE
Colliding custom properties are not handled

### ISSUE THREAD

**Issue by tik0** [DFKI-NI/syclops#15]
It just happend, that I already had an asset with a UUID as a custom property field.
I included this object multiple times and noticed, that all transformations were only applied to the first object.
Everything worked, after I deleted the custom properties of the original asset.

To prevent this in the future it might be an idea to:
1. Prefix the custom properties of syclops in an object
2. Raise an error if a custom property already exists instead of returning it, like in https://github.com/DFKI-NI/syclops/blob/8a3ce3c636bec655763c0c2dee798235b8cbac69/syclops/utility/blender_utils.py#L302

**Comment by aelmiger** [comment]
This seems to be a rare edge case, but prepending ‘POINTER_UUID’ to the UUID generated by Syclops should be sufficient to solve the problem.
The check for an existing UUID property would have to be carried out when loading the model and seems like a more complicated solution.

**Comment by aelmiger** [comment]
Should be fixed and can be tested with: https://test.pypi.org/project/syclops/1.2.4/
